#!/usr/bin/python3

import os
import sys

if os.geteuid() != 0:
    sys.stderr.write("The Pardus Parental Control Service must be run as root\n")
    exit(1)

sys.path.insert(0, "/usr/share/pardus/pardus-parental-control/src/")
import PPCService
