#!/bin/sh

set -e

# Use "sudo" group for provide access only to privileged users
PRIVILEGED_GROUP="sudo"
PREFERENCES_DIR="/var/lib/pardus/pardus-parental-control"

# Create Profiles Path
if [ ! -d "$PREFERENCES_DIR" ] ; then
    mkdir --mode=775 -p $PREFERENCES_DIR
fi

chown -R :$PRIVILEGED_GROUP $PREFERENCES_DIR

# Install smartdns service if not installed
if systemctl list-units --type=service --all | grep -q "smartdns-rs.service"; then
    systemctl stop smartdns-rs.service || true
else
    smartdns service install && systemctl stop smartdns-rs.service || true
fi

#DEBHELPER#
