#!/bin/sh

set -e

# Use "floppy" group for provide access only to privileged users
PRIVILEGED_GROUP="sudo"
PREFERENCES_DIR="/var/lib/pardus/pardus-parental-control"

# Create Profiles Path
if [ ! -d "$PREFERENCES_DIR" ] ; then
    mkdir --mode=775 -p $PREFERENCES_DIR
fi

# if $2 exists, then it is upgrading from an old package, if not exists, then installing from a new package.
if [ -z "$2" ]; then

    # Smartdns install as service
    smartdns service install && smartdns service stop

fi

#DEBHELPER#
