#!/bin/sh

set -e

APP_DIR="/usr/share/pardus/pardus-parental-control"

# if $2 exist, then it is upgrading from an old package

# if $2 is not exist, so it is removing the package itself.
if [ -z "$2" ]; then

  if [ -d "$APP_DIR" ]; then
    rm -rf $APP_DIR
  fi

  # remove smartdns service if exist:
  if systemctl list-units --type=service --all | grep -q "smartdns-rs.service"; then
    smartdns service uninstall || true
  fi

fi

#DEBHELPER#