#!/bin/sh

set -e

APP_DIR="/usr/share/pardus/pardus-parental-control"

# if $2 exist, then it is upgrading from an old package
# if $2 is not exist, so it is removing the package itself.

# Remove __pycache__ files
find $APP_DIR -name "__pycache__" -prune -exec rm -rf {} \;

# remove smartdns service if exist:
if systemctl list-units --type=service --all | grep -q "smartdns-rs.service"; then
    smartdns service uninstall || true
fi

#DEBHELPER#