#!/bin/sh
set -e

APP_DIR="/usr/share/pardus/pardus-parental-control"

case "$1" in
    remove)
        # disable restrictions before uninstall:
        /usr/share/pardus/pardus-parental-control/src/PPCActivator.py --disable || true

        ;;
    upgrade|abort-upgrade)
        # do nothing on upgrade
        ;;

    *)
        ;;
esac

# Remove __pycache__ files
if [ -d "$APP_DIR" ]; then
    find $APP_DIR -name "__pycache__" -prune -exec rm -rf {} \;
fi

#DEBHELPER#

exit 0